.\" Manpage for freenetis-http-302-redirection.1.
.\" Contact ondrej.fibich@gmail.com.in to correct errors or typos.
.TH man 1 "05 November 2013" "0.2.2" "freenetis-ssh-keys-sync man page"
.SH NAME
freenetis-ssh-keys-sync \- Updates public SSH keys of admins of the device
.SH SYNOPSIS
freenetis-ssh-keys-sync
.SH DESCRIPTION
freenetis-ssh-keys-sync is a part of FreenetIS SSK keys it servers for updating of public SSH keys of admins of the device given by his FreenetIS ID. Path to the FreenetIS and the device ID must be set in the config file.

.SH AUTHOR
Ondrej Fibich <ondrej.fibich@gmail.com>
