#!/bin/sh
# FreenetIS SSH keys DEB: actions before uninstalling of package

set -e

# remove CRON entry
rm -rf /etc/cron.d/freenetis-ssh-keys

# restart CRON
if [ -x /usr/sbin/invoke-rc.d ]; then
	invoke-rc.d cron restart 3>/dev/null || true
else
	/etc/init.d/cron restart 3>/dev/null || true
fi

